import { Question } from "./QuestionManager";

export const jeeTestData: Question[] = [
  {
    id: "jee-q1",
    text: "What is the dimensional formula for force?",
    options: ["A. [MLT⁻²]", "B. [ML²T⁻²]", "C. [MLT⁻¹]", "D. [ML²T⁻¹]"],
    correctAnswer: 0,
    hasFormulas: true,
  },
  {
    id: "jee-q2",
    text: "Which of the following is a scalar quantity?",
    options: ["A. Force", "B. Velocity", "C. Work", "D. Acceleration"],
    correctAnswer: 2,
  },
  {
    id: "jee-q3",
    text: "What is the SI unit of electric current?",
    options: ["A. Volt", "B. Ampere", "C. Ohm", "D. Watt"],
    correctAnswer: 1,
  },
  {
    id: "jee-q4",
    text: "Which law states that the induced EMF is proportional to the rate of change of magnetic flux?",
    options: [
      "A. Faraday's Law",
      "B. Lenz's Law",
      "C. Ohm's Law",
      "D. Coulomb's Law",
    ],
    correctAnswer: 0,
  },
  {
    id: "jee-q5",
    text: "What is the value of the universal gas constant (R)?",
    options: [
      "A. 8.314 J/mol·K",
      "B. 0.0821 L·atm/mol·K",
      "C. 1.987 cal/mol·K",
      "D. All of the above",
    ],
    correctAnswer: 3,
    hasFormulas: true,
  },
  {
    id: "jee-q6",
    text: "Which of the following elements has the highest electronegativity?",
    options: ["A. Fluorine", "B. Chlorine", "C. Oxygen", "D. Nitrogen"],
    correctAnswer: 0,
  },
  {
    id: "jee-q7",
    text: "What is the hybridization of the carbon atom in methane (CH₄)?",
    options: ["A. sp", "B. sp²", "C. sp³", "D. sp³d"],
    correctAnswer: 2,
    hasFormulas: true,
  },
  {
    id: "jee-q8",
    text: "Which of the following is not a thermodynamic function?",
    options: ["A. Internal Energy", "B. Enthalpy", "C. Entropy", "D. Work"],
    correctAnswer: 3,
  },
  {
    id: "jee-q9",
    text: "What is the pH of a neutral solution at 25°C?",
    options: ["A. 0", "B. 7", "C. 14", "D. 1"],
    correctAnswer: 1,
  },
  {
    id: "jee-q10",
    text: "Which of the following is a strong acid?",
    options: [
      "A. Acetic acid",
      "B. Hydrochloric acid",
      "C. Carbonic acid",
      "D. Phosphoric acid",
    ],
    correctAnswer: 1,
  },
  {
    id: "jee-q11",
    text: "What is the unit of capacitance?",
    options: ["A. Farad", "B. Ohm", "C. Henry", "D. Tesla"],
    correctAnswer: 0,
  },
  {
    id: "jee-q12",
    text: "Which of the following is a vector quantity?",
    options: ["A. Speed", "B. Distance", "C. Displacement", "D. Energy"],
    correctAnswer: 2,
  },
  {
    id: "jee-q13",
    text: "What is the formula for kinetic energy?",
    options: ["A. ½mv²", "B. mgh", "C. ½kx²", "D. Fd"],
    correctAnswer: 0,
    hasFormulas: true,
  },
  {
    id: "jee-q14",
    text: "Which of the following is not a type of radiation?",
    options: ["A. Alpha", "B. Beta", "C. Gamma", "D. Delta"],
    correctAnswer: 3,
  },
  {
    id: "jee-q15",
    text: "What is the principle behind the working of a transformer?",
    options: [
      "A. Electromagnetic induction",
      "B. Mutual induction",
      "C. Self-induction",
      "D. Faraday's law",
    ],
    correctAnswer: 1,
  },
  {
    id: "jee-q16",
    text: "Which of the following is a noble gas?",
    options: ["A. Helium", "B. Hydrogen", "C. Nitrogen", "D. Oxygen"],
    correctAnswer: 0,
  },
  {
    id: "jee-q17",
    text: "What is the formula for the area of a circle?",
    options: ["A. πr²", "B. 2πr", "C. πd", "D. πr"],
    correctAnswer: 0,
    hasFormulas: true,
  },
  {
    id: "jee-q18",
    text: "Which of the following is a non-metal?",
    options: ["A. Sodium", "B. Magnesium", "C. Chlorine", "D. Aluminum"],
    correctAnswer: 2,
  },
  {
    id: "jee-q19",
    text: "What is the unit of power?",
    options: ["A. Joule", "B. Watt", "C. Newton", "D. Pascal"],
    correctAnswer: 1,
  },
  {
    id: "jee-q20",
    text: "Which of the following is a primary color of light?",
    options: ["A. Red", "B. Green", "C. Blue", "D. All of the above"],
    correctAnswer: 3,
  },
];
