import { Question } from "./QuestionManager";

export const upscTestData: Question[] = [
  {
    id: "upsc-q1",
    text: "भारतीय संविधान में मौलिक अधिकार किस देश के संविधान से प्रेरित हैं?",
    options: ["A. यूएसए", "B. यूके", "C. कनाडा", "D. ऑस्ट्रेलिया"],
    correctAnswer: 0,
    language: "hindi",
  },
  {
    id: "upsc-q2",
    text: "भारत का सबसे बड़ा नदी द्वीप कौन सा है?",
    options: ["A. मजुली", "B. श्रीरंगम", "C. उल्लूरु", "D. भवानी"],
    correctAnswer: 0,
    language: "hindi",
  },
  {
    id: "upsc-q3",
    text: "भारतीय राष्ट्रीय कांग्रेस की स्थापना किस वर्ष हुई थी?",
    options: ["A. 1885", "B. 1905", "C. 1920", "D. 1947"],
    correctAnswer: 0,
    language: "hindi",
  },
  {
    id: "upsc-q4",
    text: "भारत का सबसे बड़ा रेगिस्तान कौन सा है?",
    options: ["A. थार", "B. सहारा", "C. गोबी", "D. कालाहारी"],
    correctAnswer: 0,
    language: "hindi",
  },
  {
    id: "upsc-q5",
    text: "भारत का सबसे ऊँचा बांध कौन सा है?",
    options: [
      "A. टिहरी बांध",
      "B. भाखड़ा बांध",
      "C. सरदार सरोवर बांध",
      "D. हीराकुंड बांध",
    ],
    correctAnswer: 0,
    language: "hindi",
  },
  {
    id: "upsc-q6",
    text: "भारत का राष्ट्रीय पशु कौन सा है?",
    options: ["A. बाघ", "B. हाथी", "C. शेर", "D. गाय"],
    correctAnswer: 0,
    language: "hindi",
  },
  {
    id: "upsc-q7",
    text: "भारत का सबसे बड़ा बंदरगाह कौन सा है?",
    options: [
      "A. जवाहरलाल नेहरू बंदरगाह",
      "B. चेन्नई बंदरगाह",
      "C. कोलकाता बंदरगाह",
      "D. मुंबई बंदरगाह",
    ],
    correctAnswer: 0,
    language: "hindi",
  },
  {
    id: "upsc-q8",
    text: "भारत का सबसे बड़ा गुफा मंदिर कौन सा है?",
    options: ["A. अजंता", "B. एलोरा", "C. एलीफेंटा", "D. कार्ला"],
    correctAnswer: 1,
    language: "hindi",
  },
  {
    id: "upsc-q9",
    text: "भारत का सबसे बड़ा वन्यजीव अभयारण्य कौन सा है?",
    options: ["A. काजीरंगा", "B. गिर", "C. सुंदरबन", "D. रणथंभौर"],
    correctAnswer: 0,
    language: "hindi",
  },
  {
    id: "upsc-q10",
    text: "भारत का सबसे बड़ा झील कौन सा है?",
    options: ["A. वूलर झील", "B. चिल्का झील", "C. डल झील", "D. सांभर झील"],
    correctAnswer: 0,
    language: "hindi",
  },
  {
    id: "upsc-q11",
    text: "भारत का सबसे बड़ा रेलवे स्टेशन कौन सा है?",
    options: [
      "A. हावड़ा जंक्शन",
      "B. नई दिल्ली",
      "C. चेन्नई सेंट्रल",
      "D. मुंबई सेंट्रल",
    ],
    correctAnswer: 0,
    language: "hindi",
  },
  {
    id: "upsc-q12",
    text: "भारत का सबसे बड़ा हवाई अड्डा कौन सा है?",
    options: [
      "A. इंदिरा गांधी अंतर्राष्ट्रीय हवाई अड्डा",
      "B. छत्रपति शिवाजी अंतर्राष्ट्रीय हवाई अड्डा",
      "C. केम्पेगौड़ा अंतर्राष्ट्रीय हवाई अड्डा",
      "D. राजीव गांधी अंतर्राष्ट्रीय हवाई अड्डा",
    ],
    correctAnswer: 0,
    language: "hindi",
  },
  {
    id: "upsc-q13",
    text: "भारत का सबसे बड़ा बांध कौन सा है?",
    options: [
      "A. टिहरी बांध",
      "B. भाखड़ा बांध",
      "C. सरदार सरोवर बांध",
      "D. हीराकुंड बांध",
    ],
    correctAnswer: 0,
    language: "hindi",
  },
  {
    id: "upsc-q14",
    text: "भारत का सबसे बड़ा नदी द्वीप कौन सा है?",
    options: ["A. मजुली", "B. श्रीरंगम", "C. उल्लूरु", "D. भवानी"],
    correctAnswer: 0,
    language: "hindi",
  },
  {
    id: "upsc-q15",
    text: "भारत का सबसे बड़ा रेगिस्तान कौन सा है?",
    options: ["A. थार", "B. सहारा", "C. गोबी", "D. कालाहारी"],
    correctAnswer: 0,
    language: "hindi",
  },
  {
    id: "upsc-q16",
    text: "भारत का सबसे ऊँचा बांध कौन सा है?",
    options: [
      "A. टिहरी बांध",
      "B. भाखड़ा बांध",
      "C. सरदार सरोवर बांध",
      "D. हीराकुंड बांध",
    ],
    correctAnswer: 0,
    language: "hindi",
  },
  {
    id: "upsc-q17",
    text: "भारत का राष्ट्रीय पशु कौन सा है?",
    options: ["A. बाघ", "B. हाथी", "C. शेर", "D. गाय"],
    correctAnswer: 0,
    language: "hindi",
  },
  {
    id: "upsc-q18",
    text: "भारत का सबसे बड़ा बंदरगाह कौन सा है?",
    options: [
      "A. जवाहरलाल नेहरू बंदरगाह",
      "B. चेन्नई बंदरगाह",
      "C. कोलकाता बंदरगाह",
      "D. मुंबई बंदरगाह",
    ],
    correctAnswer: 0,
    language: "hindi",
  },
  {
    id: "upsc-q19",
    text: "भारत का सबसे बड़ा गुफा मंदिर कौन सा है?",
    options: ["A. अजंता", "B. एलोरा", "C. एलीफेंटा", "D. कार्ला"],
    correctAnswer: 1,
    language: "hindi",
  },
  {
    id: "upsc-q20",
    text: "भारत का सबसे बड़ा वन्यजीव अभयारण्य कौन सा है?",
    options: ["A. काजीरंगा", "B. गिर", "C. सुंदरबन", "D. रणथंभौर"],
    correctAnswer: 0,
    language: "hindi",
  },
];
